# This rule is for any direct visit to a path like /negotiator.
# It serves your app's main HTML file, allowing React to take over.
# This is the standard rule for all modern single-page apps.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200